services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    ports:
      - 8000:8000
    networks:
      - backend_network
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    networks:
      - backend_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - omunga-postgres:/var/lib/postgresql/data

  redis:
    container_name: redis-db
    image: redis
    restart: unless-stopped
    networks:
      - backend_network
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

networks:
  backend_network:
    driver: bridge

volumes:
  omunga-postgres:
  redis:
    driver: local
